fb55/css-select

- test/api.js
Commit 0f0daad251094287a6223ba24467bf073dc2c0fe introduced a breaking
change in this library's functionality: the selection API no longer
matches against elements specified via an array when those elements are
not root nodes.
There were previously no tests asserting this behavior, but the change
should be considered "breaking" for two reasons:
1. it is inconsistent--root nodes may still be queried in this way
2. the project's documentation implies the original behavior:
> ### `CSSselect(query, elems, options)`
>
> Queries `elems`, returns an array containing all matches.
>
> - `query` can be either a CSS selector or a function.
> - `elems` can be either an array of elements, or a single element. If
>    it is an element, its children will be queried.
> - `options` is described below.
Add …
> Add failing test to demonstrate regression

- README.md
- lib/pseudos.js
- test/icontains.js
As discussed in [issue 33](https://github.com/fb55/css-select/issues/33), with tests.
One of the tests fails and needs a corresponding fix in css-what to strip the quotes of `icontains` data. I have opened a separate [PR](https://github.com/fb55/css-what/pull/15) for that issue.
> pseudos: implement :icontains, case-insensitive version of :contains

- lib/compile.js
- lib/general.js
- test/qwery/index.js
This pull request is intended to fix [an issue](https://github.com/cheeriojs/cheerio/issues/728) referenced in Cheerio repository. 
The unit tests used to demonstrate the regression can be found in [this other pull request](https://github.com/fb55/css-select/pull/30).
Basically, if the query's context is a single element, and if the selector matches this one, it should not be added to the results. However, if the context is an array of elements, then these elements can be matched by the query.
The issue was due to `absolutize()` introduced in v1.1.0. This function adds `":scope "` to the selector, and because of the descendant selector `" "`, "root" element to which is applied the query could not be reached. This is fine if the context is a single element, but this is not the expected …
> Fix regression, include self while querying array 

- lib/compile.js
- lib/general.js
This is a continuation of [my previous pull request](https://github.com/fb55/css-select/pull/37).
I am glad I could you. 
But I said my changes looked ugly, so I tried to improve it.
This commit looks more elegant and efficient than the previous one which added complexity to the code and parameters while trying to make a special descendant selector "flexible".
I think the best is simply to add a new "flexible descendant" selector, so I created a new type of descendant token which accepts element itself. Then, I replace classic descendant within the rule if conditions are fulfilled.
> Propose an alternative way to solve regression

- index.js
- lib/compile.js
- lib/pseudos.js
- test/nwmatcher/index.js
- test/qwery/index.js
- test/sizzle/selector.js
So, partly because css-select is "right-to-left execution", it was not able to properly find siblings elements when the selector was starting with `+` (or `~`) and when the reference element was passed to the context.
Indeed, the query function is applied to each elements and children contained in the context object, but siblings and adjacent are not included, so these elements could not be tested, and could not be returned by the `select` function.
The way to solve this is to extend the `elems` array with the next siblings of each of its elements. Thanks to the tokens `:scope` which are prepended during the compilation, the unwanted elements from siblings's children will not be queried. Of course, we do not want to do this for each query, because this may be very slow. So, we have to …
> Fix #42 by adding siblings elements if needed

- index.d.ts
- package.json
Hi, I use this project with a project written in typescript so I made a typescript definition for it.
If you're not familiar with typescript there's two approaches to adding a public definition file. The preferred approach is to add it to the project and ship with it. This way new changes to the API can be kept in sync. The second approach is that this definition can be shipped as a separate node module and maintained by the typescript community at https://github.com/DefinitelyTyped/DefinitelyTyped
If you're not interested in accepting this PR then please let me know and I'll take the community driven approach instead. If you are, and would like help maintaining the typescript definition when the public API changes, I'm willing to do so.
> Add typescript definition for public API.

- lib/general.js
- package.json
This PR works by keeping a cache of of elements inside each descendant function for which the rest of the selector doesn't match. 
* https://github.com/dbuezas/css-select-test
* https://rawgit.com/dbuezas/css-select-test/master/test.html
(wait a couple of seconds to see results table)
* https://github.com/cheeriojs/cheerio/issues/1118
* https://github.com/fb55/css-select/issues/93
* Native implementation of Set in chrome seems to be a tad faster than the one in Node.
* `es6-set` is just a polyfill and uses native implementation if available
> avoid exponential time on selectors with many descendants 

- .eslintrc
- index.js
- lib/attributes.js
- lib/compile.js
- lib/general.js
- lib/procedure.json
- lib/pseudos.js
- test/api.js
- test/attributes.js
- test/icontains.js
- test/nwmatcher/index.js
- test/qwery/index.js
- test/sizzle/data/testinit.js
- test/sizzle/selector.js
- test/test.js
- test/tools/bench.js
- test/tools/slickspeed.js
This way there is no performance difference if another adapter is used.
Breaking change: Pseudos now take the adapter as the second argument,
and arguments as the third. Filters aren’t checked anymore if they have
the required number of arguments
Also formats most of the codebase with prettier.
> Use options to pass through adapters

- lib/compile.js
- test/sizzle/data/index.html
- test/sizzle/selector.js
`:scope > label` was absolutized into `:scope :scope > label` when used in a scope i.e. when using `selectOne(':scope > label', selectOne('#scope'))`
I don't understand the current terminology since items of a `token` are named `t` and I suspect the error originates from somewhere else. But at least it fixed the test which is valid in a browser: 
1. Goto https://o9vrw.csb.app/
2. Enter `:scope > label`
3. DOM will output HTMLLabelElement while css-select returns null
Code available in https://codesandbox.io/s/css-select-vs-elementqueryselector-o9vrw
> fix: :scope not matching when selecting in a scope

- README.md
- index.d.ts
- lib/pseudos.js
- test/qwery/index.js
Pseudos like element state `hover`, `active`, `visited`, etc can be supported conditionally.
This PR enables such pseudos to be supported only if associated Adapter method is implemented.
For example:
`hover` pseudo may give results, only if `isHovered` is implemented in given Adapter APIs. Otherwise, `hover` will result into `falseFunc` and will give empty result.
This logic can be improved in various ways. Please review once and see my comments on code and let me know if I am going in right direction.
I will be updating `Readme` and Test Cases once logic is finalised.
Resolves: #80
> New: Add `pseudos` that depend on optional Adapter APIs

- src/attributes.ts
- test/attributes.ts
When `ignoreCase` is `true`.
Necessary for #390
> fix(attributes): Fix `!=` ignoring elements without attribute

- src/attributes.ts
- src/compile.ts
- src/general.ts
- src/index.ts
- src/pseudo-selectors/aliases.ts
- src/pseudo-selectors/filters.ts
- src/pseudo-selectors/index.ts
- src/pseudo-selectors/pseudos.ts
- src/pseudo-selectors/subselects.ts
- test/api.ts
Aliases are pseudos that can be expressed as a selector.
Corrects the implementation for several pseudos, eg. `:disabled`, `:checked` and `:required`.
Also fixes `:is` with traversals.
> feat(pseudos): Introduce aliases

- src/compile.ts
- src/general.ts
- src/index.ts
- src/pseudo-selectors/filters.ts
- src/pseudo-selectors/index.ts
- src/pseudo-selectors/subselects.ts
- src/types.ts
- test/api.ts
This should make it possible to pass document nodes.
> refactor: Allow plain nodes as context

- src/index.ts
- test/api.ts
This bug was hidden due to `removeSubsets` ordering elements.
Fixes #655
> fix: Don't add siblings multiple times in `appendNextSiblings`

- package-lock.json
- package.json
- src/attributes.ts
- src/compile.ts
- src/general.ts
- src/procedure.ts
- src/pseudo-selectors/index.ts
- src/sort.ts
- src/types.ts
- test/api.ts
css-what@6 dropped support for lowercasing tag & attribute names. For backwards-compatibility, these options were now added to css-select. Note that this will be removed again in a future release.
Also, introduced a new `quirksMode` option that will match .class and #ID values case-insensitively.
> feat: Upgrade to css-what@6, add quirks mode option

- package-lock.json
- package.json
- src/general.ts
- src/index.ts
- src/types.ts
- test/api.ts
- test/icontains.ts
- test/nwmatcher.ts
- test/qwery.ts
- test/sizzle.ts
- test/tools/helper.ts
- test/tools/sizzle-testinit.ts
BREAKING: We will now filter for `isTag` whenever we look for a parent. This will prevent issues where we try to check a `Document` object for non-existent keys.
> BREAKING: Bump dependencies, update types

- src/pseudo-selectors/index.ts
- test/api.ts
- test/nwmatcher.ts
- test/pseudo-classes.ts
Fixes #741
BREAKING: The error message for unknown pseudo classes has changed.
Also adds several tests, mostly for pseudo-classes.
> fix: Throw an error for `:host-context`

- README.md
- src/index.ts
- src/pseudo-selectors/index.ts
- src/pseudo-selectors/pseudos.ts
- src/types.ts
- test/api.ts
- test/qwery.ts
This option allows users to specify pseudo-classes. This approach is favoured over extending the internal `filters`, `pseudos` and `aliases` objects, as different libraries can define their own versions of pseudo-classes.
Extending `filters`, `pseudos` and `aliases` is now deprecated.
> feat: Add `pseudos` option

- src/pseudo-selectors/pseudos.ts
- test/pseudo-classes.ts
Fixes https://github.com/cheeriojs/cheerio/issues/2561
Note that the behaviour of `:empty` has changed in CSS4 — whitespace was previously not ignored.
Also note that this changes the behaviour of the `:parent` pseudo-class (which is a jQuery extension), as jQuery defines it as the opposite of `:empty`.
> fix(pseudos): Allow whitespace in `:empty`

- src/compile.ts
- src/helpers/querying.ts
- src/helpers/selectors.ts
- src/index.ts
- src/pseudo-selectors/subselects.ts
- test/pseudo-classes.ts
`:has(:scope)` and `:has(> div)` were both previously cached, which they shouldn't have been.
As a bit of cleanup, this also moves the compile functions directly to the index file.
> fix(pseudos): Don't cache context sensitive :has

- src/helpers/querying.ts
The node stack in query methods is now an array of arrays.
> refactor(querying): Don't flatten node stack
